import { ListType } from "./types";
import { rawHTMLLink } from "./listHelper";

export const DLCQuestsList: Array<ListType> = [
    {
      id: "",
      name: "Sir Ansbach",
      requirements: [
        { id: "", description: "Speak with Sir Ansbach at the Main Gate Cross - Site of Grace" },
        { id: "", description: "Break Miquella's charm" },
        { id: "", description: "Speak to Sir Ansbach at the Main Gate Cross - Site of Grace" },
        { id: "", description: "Travel to the Shadow Keep and speak to him at the Storehouse, First Floor" },
        { id: "", description: "Hand over the Secret Rite Scroll to Sir Ansbach" },
        { id: "", description: "Continue Needle Knight Leda's questline" },
        { id: "", description: "Respond to the summons in the Storehouse" },
        { id: "", description: "Join the NPC battle in Enir-Ilim" },
        { id: "", description: "Defeat the final boss in Enir-Ilim" },
      ],
    },
    {
      id: "",
      name: "Redmane Freyja",
      requirements: [
        { id: "", description: "Speak with Redmane Freyja at the Three-Path Cross Site of Grace." },
        { id: "", description: "Speak with Freyja after defeating the Divine Beast." },
        { id: "", description: "Break Miquella's charm." },
        { id: "", description: "Speak to Freyja and exhaust her dialogues at the Three-Path Cross Site of Grace." },
        { id: "", description: "Look for Freyja in the Seventh Floor Storehouse." },
        { id: "", description: "Obtain the Secret Rite Scroll." },
        { id: "", description: "Tell Sir Ansbach about Freyja in the First Floor Storehouse." },
        { id: "", description: "Acquire the Letter for Freyja from Sir Ansbach." },
        { id: "", description: "Give the letter to Freyja and exhaust her dialogue to receive the Golden Lion Shield." },
        { id: "", description: "Fight the NPC allies in Enir-Ilim." },
      ],
    },
    {
      id: "",
      name: "Hornsent",
      requirements: [
        { id: "", description: "Speak with Hornsent by the Three-Path Cross Site of Grace" },
        { id: "", description: "Speak with Hornsent at the Highroad Cross Site of Grace" },
        { id: "", description: "Break Miquella's charm" },
        { id: "", description: "Speak with Hornsent after the charm is broken" },
        { id: "", description: "Help Leda decide who she should go after" },
        { id: "", description: "Assist Hornsent to fight against Leda" },
        { id: "", description: "Optional, can skip both fights" },
        { id: "", description: "Summon Hornsent to fight against Messmer, The Impaler" },
        { id: "", description: "Speak with Hornsent in the boss room" },
        { id: "", description: "Defeat Hornsent during his invasion." },
      ],
    },
    {
      id: "",
      name: "Igon",
      requirements: [
        { id: "", description: "Speak with Igon near the Pillar Path Waypoint Site of Grace" },
        { id: "", description: "Discover Jagged Peak" },
        { id: "", description: "(Optional) Defeat the first Jagged Peak Drake" },
        { id: "", description: "Reach the Grand Altar of Dragon Communion" },
        { id: "", description: "Defeat the two Jagged Peak Drakes" },
        { id: "", description: "Speak with Igon and obtain Igon's Furled Finger" },
        { id: "", description: "(Optional) Defeat the Ancient Dragon Senessax" },
        { id: "", description: "(Optional) Summon Igon to assist you in defeating Bayle the Dread" },
      ],
    },
    {
      id: "",
      name: "Moore",
      requirements: [
        { id: "", description: "Meet Moore outside Belurat, Tower Settlement" },
        { id: "", description: "Meet Thiollier" },
        { id: "", description: "Speak with Moore after breaking Miquella's charm" },
      ],
    },
    {
      id: "",
      name: "Needle Knight Leda",
      requirements: [
        { id: "", description: "Speak with Leda at the Cocoon of the Empyrean in the base game" },
        { id: "", description: "Receive Leda's Message at Belurat Tower Settlement" },
        { id: "", description: "Receive Leda's Message at Castle Ensis" },
        { id: "", description: "Speak with Leda by the Highroad Cross Site of Grace" },
        { id: "", description: "Break Miquella's charm by approaching Shadow Keep or crossing the bridge east of Bonny Village" },
        { id: "", description: "Speak with Leda at the Highroad Cross Site of Grace" },
        { id: "", description: "Enter Shadow Keep" },
        { id: "", description: "Speak with Leda at the Highroad Cross and decide who you want to investigate" },
        { id: "", description: "Assist Leda or assist Hornsent" },
        { id: "", description: "Continue Sir Ansbach's questline" },
        { id: "", description: "Assist Leda or assist Sir Ansbach" },
        { id: "", description: "Fight the NPC battle in Enir-Ilim" },
      ],
    },
    {
        id: "",
        name: "Thiollier",
        requirements: [
          { id: "", description: "Speak with Thiollier at the Pillar Path Cross Site of Grace" },
          { id: "", description: "Break Miquella's charm" },
          { id: "", description: "Look for St. Trina in the Garden of Deep Purple" },
          { id: "", description: "Drink and die from St. Trina's nectar 4 times" },
          { id: "", description: "Pass on St.Trina's words to Thiollier." },
          { id: "", description: "Defeat Thiollier when he invades you" },
          { id: "", description: "Drink St. Trina's once more and speak with Thiollier" },
          { id: "", description: "(Optional) Summon Thiollier to defeat the NPC allies at Enir-Ilim" },
          { id: "", description: "(Optional) Summon Thiollier to defeat the final boss" },
        ],
      },
      {
        id: "",
        name: "Hornsent Grandam",
        requirements: [
          { id: "", description: "Look for the Storeroom Key in Belurat." },
          { id: "", description: "Speak with Hornsent Grandam in the Storeroom." },
          { id: "", description: "Defeat the Divine Beast Dancing Lion." },
          { id: "", description: "Wear the Divine Beast Head and speak with Hornsent Grandam." },
          { id: "", description: "Reload the area and speak with Hornsent Grandam again." },
          { id: "", description: "Defeat Messmer the Impaler, and speak with Hornsent Grandam once more." },
        ],
      },
      {
        id: "",
        name: "Dryleaf Dane",
        requirements: [
          { id: "", description: "Acquire Monk's Missive and May the Best Win" },
          { id: "", description: "Duel with Dryleaf Dane at Moorth Ruins" },
          { id: "", description: "Defeat the NPC allies at Enir-Ilim" },
          { id: "", description: "Obtain Dryleaf Dane's equipment" },
        ],
      },
      {
        id: "",
        name: "Count Ymir, High Priest",
        requirements: [
          { id: "", description: "Speak with Count Ymir, High Priest at the Cathedral of Manus Metyr" },
          { id: "", description: "Ring the bell in the Finger Ruins of Rhia" },
          { id: "", description: "Head back to Ymir and obtain Ruins Map (2nd)" },
          { id: "", description: "Find Scaduview" },
          { id: "", description: "Ring the bell in the Finger Ruins of Dheo" },
          { id: "", description: "Head back to Ymir to obtain Ruins Map (3rd)" },
          { id: "", description: "Ring the bell in the Finger Ruins of Miyr" },
          { id: "", description: "Defeat Metyr Mother of Fingers" },
          { id: "", description: "Defeat Jolan and Ymir" },
          { id: "", description: "Obtain the Cherishing Fingers" },
        ],
      },
      {
        id: "",
        name: "Dragon Communion Priestess",
        requirements: [
          { id: "", description: "Devour the Draconic Essence that the Priestess offers" },
          { id: "", description: "Decide to give Thiollier's Concoction to her or not" },
          { id: "", description: "Defeat Bayle the Dread" },
          { id: "", description: "Return to the Grand Altar of Dragon Communion after defeating Bayle" },
        ],
      },
      {
        id: "",
        name: "Swordhand of Night Jolán",
        requirements: [
          { id: "", description: "Speak with Count Ymir at the Cathedral of Manus Metyr" },
          { id: "", description: "Speak with Jolan after getting the Ruins Map" },
          { id: "", description: "Continue Count Ymir's questline until you finish blowing 2 whistles" },
          { id: "", description: "Go back to the Cathedral, talk" },
          { id: "", description: "Go down the ladder and defeat Metyr, Mother of Fingers" },
          { id: "", description: "Return to the Cathedral to fight Jolan and Count Ymir" },
          { id: "", description: "Speak with Jolan after defeating Ymir" },
          { id: "", description: "Obtain the Iris of Grace or Iris of Occultation" },
          { id: "", description: "Give one of the Irises to Jolan" },
          { id: "", description: "Make your way to Rabbath's Rise to reunite with Jolan and Anna" },
        ],
      },
      {
        id: "",
        name: "Fire Knight Queelign",
        requirements: [
          { id: "", description: "Get invaded by Fire Knight Queelign Twice" },
          { id: "", description: "Collect the Irises" },
          { id: "", description: "Look for Queelign in Shadow Keep" },
        ],
      },
      {
        id: "",
        name: "St. Trina",
        requirements: [
          { id: "", description: "Break Miquella's great rune" },
          { id: "", description: "Discover the Stone Coffin Fissure" },
          { id: "", description: "Defeat the Putrescent Knight" },
          { id: "", description: "Drink and die from St. Trina's nectar four times" },
          { id: "", description: "(Optional) Pass on the words of St. Trina to Thiollier, defeat him when he invades, and then pass on her words to him again" },
          { id: "", description: "Defeat the final boss in Enir-Ilim" },
        ],
      },
    
  ];
  